after_script:
- rm -rf logs
before_install:
- npm update -g npm
before_script:
- mkdir logs && touch logs/access.log
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: RreGrvQwhyEbA3+Ld4p3RCqROYU7vft2DZ0V8thLwLgLnzWm6pWy5rYrmmQh6B+YX/HQvF0sT/MSWHGk5A8IL9drVe51NB4zNDC3mWzPCPcFjScABKQogHtx6qXqTMBbJ43UNZ0j/AigxasrZf21tT28uLGTwcIJzfYcCWh20YbP3frOWn19tqlmj3sC3xGRwFkLl11aN7QQlZ2oFojFngD2u821M87lfXfCqfMVWYJPgmVReA91P9cnSM06tdvHmELLDDQYy/4ZH9V1CkyRlnj27MN1Lo8XZQaCjxzN10jECi8YEyZBWUjwg2SvfwJxkLNCMXYqrtAzgaeTAi/roG++dR7wxPk1sezyHVUshvggEpZEDZEzbZjc/qEgVQwNlEqW/x9mYL2kwEmC9G0Iyi8gPP7trDFhDSSS+FxcgmIUjRL2VORLUdeUnVq9URuOV7G5V1ncPDays+NgLB6sdicvdj7MiPSScKOon9qzR2IODrwCqb9AtSzZzGqqFz1eLwcvI4ncc8c8rr3NKqcsY1gd2nf1iL6izq6wJjGvqVPKWs9wKFMaeXvPO7Pl0JQYQAvDSU+vmEBjXwP8SAbgesN6T9zhCq+yU9cXEAZSQRAxS/uggMGA1XuxzrzKlDdy2PfbiQtB7YPgLgXTF1iGRmSGAYaSlKmymgSbiNs1p34=
  app: call-by-meaning
  on:
    repo: iamnapo/CallByMeaning
  skip_cleanup: true
language: node_js
node_js:
- node
notifications:
  email: false
sudo: false
